name: CMake Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.24.2'  # Обновите до последней стабильной версии CMake

    - name: Configure the build
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest
