name: Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y cmake

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest
