name: CMake Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка кода
      uses: actions/checkout@v3

    - name: Установка CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.24.2'  # Укажите версию CMake, которую хотите использовать

    - name: Конфигурация сборки
      run: cmake -S MaxValueFinder -B MaxValueFinder/build  # Укажите путь к CMakeLists.txt

    - name: Сборка проекта
      run: cmake --build MaxValueFinder/build

    - name: Запуск тестов
      run: |
        cd MaxValueFinder/build
        ctest
